# **USA Crime Dataset**
---

> **uploading data**

In [29]:
!wget -O usa_crimes_dataset.csv 'https://raw.githubusercontent.com/narminzeynally/usa-crimes-dataset-analysis/refs/heads/main/data/usa_crimes_dataset_dirty.csv'

--2024-10-20 14:38:40--  https://raw.githubusercontent.com/narminzeynally/usa-crimes-dataset-analysis/refs/heads/main/data/usa_crimes_dataset_dirty.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 95619252 (91M) [text/plain]
Saving to: ‘usa_crimes_dataset.csv’

usa_crimes_dataset. 100%[===================>]  91.19M   277MB/s    in 0.3s

2024-10-20 14:38:43 (277 MB/s) - ‘usa_crimes_dataset.csv’ saved [95619252/95619252]

> **importing dataset**

In [30]:
import pandas as pd
import matplotlib.pyplot as plt

usa_crimes_dataset = pd.read_csv('/content/usa_crimes_dataset.csv')
usa_crimes_dataset

<ipython-input-30-555c5ece34a5>:4: DtypeWarning: Columns (1,18) have mixed types. Specify dtype option on import or set low_memory=False.
  usa_crimes_dataset = pd.read_csv('/content/usa_crimes_dataset.csv')

,Incident ID,Offence Code,CR Number,Dispatch Date / Time,NIBRS Code,Victims,Crime Name1,Crime Name2,Crime Name3,Police District Name,...,Street Prefix,Street Name,Street Suffix,Street Type,Start_Date_Time,End_Date_Time,Latitude,Longitude,Police District Number,Location
0,201202980,3550,180042096,08/23/2018 09:52:08 PM,35B,1,Crime Against Society,Drug Equipment Violations,DRUGS - NARCOTIC EQUIP - POSSESS,GERMANTOWN,...,NaN,MIDDLEBROOK,NaN,RD,08/23/2018 09:52:00 PM,NaN,39.177744,-77.265619,5D,"(39.1777, -77.2656)"
1,201181293,3522,180015424,03/30/2018 01:00:55 AM,35A,1,Crime Against Society,Drug/Narcotic Violations,DRUGS - OPIUM OR DERIVATIVE - POSSESS,BETHESDA,...,NaN,WOODMONT,NaN,AVE,03/30/2018 01:01:00 AM,NaN,38.992693,-77.097063,2D,"(38.9927, -77.0971)"
2,201181293,3562,180015424,03/30/2018 01:00:55 AM,35A,1,Crime Against Society,Drug/Narcotic Violations,DRUGS - MARIJUANA - POSSESS,BETHESDA,...,NaN,WOODMONT,NaN,AVE,03/30/2018 01:01:00 AM,NaN,38.992693,-77.097063,2D,"(38.9927, -77.0971)"
3,201193163,3520,180029476,06/14/2018 10:26:45 PM,35A,1,Crime Against Society,Drug/Narcotic Violations,DRUGS - OPIUM OR DERIVATIVE - SELL,MONTGOMERY VILLAGE,...,NaN,QUINCE ORCHARD,NaN,RD,06/14/2018 10:26:00 PM,06/15/2018 03:00:00 AM,39.147954,-77.218189,6D,"(39.148, -77.2182)"
4,201204355,2204,180043926,09/03/2018 12:06:54 PM,220,1,Crime Against Property,Burglary/Breaking and Entering,BURGLARY - NO FORCED ENTRY-RESIDENTIAL,BETHESDA,...,NaN,FALSTONE,NaN,AVE,09/02/2018 11:30:00 PM,09/03/2018 12:30:00 AM,38.966174,-77.096561,2D,"(38.9662, -77.0966)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
306089,201320571,1399,210006666,02/21/2021 07:25:28 AM,13B,1,Crime Against Person,Simple Assault,ASSAULT - 2ND DEGREE,MONTGOMERY VILLAGE,...,NaN,TRANSHIRE,NaN,RD,02/20/2021 08:00:00 PM,NaN,39.172701,-77.197340,6D,"(39.1727, -77.1973)"
306090,201329875,2305,210017101,05/06/2021 10:54:47 PM,23F,1,Crime Against Property,Theft From Motor Vehicle,LARCENY - FROM AUTO,WHEATON,...,NaN,ATHERTON,NaN,DR,05/06/2021 03:15:00 AM,NaN,39.059672,-77.075995,4D,"(39.0597, -77.076)"
306091,201329751,5016,210016952,05/05/2021 10:38:58 PM,90Z,1,Crime Against Society,All Other Offenses,OBSTRUCT GOVT - VIOLATION OF A COURT ORDER,GERMANTOWN,...,NaN,BALTUSROL,NaN,DR,05/05/2021 10:38:00 PM,NaN,39.199722,-77.273039,5D,"(39.1997, -77.273)"
306092,201323117,9099,210009468,03/13/2021 12:07:14 PM,90Z,1,Crime Against Society,All Other Offenses,ALL OTHER OFFENSES,SILVER SPRING,...,NaN,FENTON,NaN,ST,03/13/2021 01:35:00 PM,NaN,38.985813,-77.022915,3D,"(38.9858, -77.0229)"
306093,201327806,2305,210014587,04/19/2021 02:17:29 PM,23F,1,Crime Against Property,Theft From Motor Vehicle,LARCENY - FROM AUTO,BETHESDA,...,NaN,NEWPORT MILL,NaN,RD,04/18/2021 04:00:00 PM,04/19/2021 12:00:00 PM,39.037115,-77.072485,2D,"(39.0371, -77.0725)"

> **checking duplicates**

In [61]:
duplicates = usa_crimes_dataset[usa_crimes_dataset.duplicated()]
duplicates

Empty DataFrame
Columns: [id, incident_id, offence_code, cr_number, nibrs_code, victims, crime_type, crime_category, crime_information, police_district_name, city, state, zip_code, agency, place, sector, beat, street_name, street_type, latitude, longitude, police_district_number, location, dispatch_date, dispatch_time, start_date, start_time, start_part_of_day, start_day_of_week]
Index: []

[0 rows x 29 columns]

> **information about dataset**

In [31]:
usa_crimes_dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 306094 entries, 0 to 306093
Data columns (total 30 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   Incident ID             306094 non-null  int64
 1   Offence Code            306094 non-null  object
 2   CR Number               306094 non-null  int64
 3   Dispatch Date / Time    257065 non-null  object
 4   NIBRS Code              306094 non-null  object
 5   Victims                 306094 non-null  int64
 6   Crime Name1             305822 non-null  object
 7   Crime Name2             305822 non-null  object
 8   Crime Name3             305822 non-null  object
 9   Police District Name    306000 non-null  object
 10  Block Address           279888 non-null  object
 11  City                    304818 non-null  object
 12  State                   306094 non-null  object
 13  Zip Code                302915 non-null  float64
 14  Agency                  306094 non-null  object
 15  Place                   306094 non-null  object
 16  Sector                  304564 non-null  object
 17  Beat                    304564 non-null  object
 18  PRA                     305855 non-null  object
 19  Address Number          279985 non-null  float64
 20  Street Prefix           13631 non-null   object
 21  Street Name             306093 non-null  object
 22  Street Suffix           5432 non-null    object
 23  Street Type             305755 non-null  object
 24  Start_Date_Time         306094 non-null  object
 25  End_Date_Time           144436 non-null  object
 26  Latitude                306094 non-null  float64
 27  Longitude               306094 non-null  float64
 28  Police District Number  306094 non-null  object
 29  Location                306094 non-null  object
dtypes: float64(4), int64(3), object(23)
memory usage: 70.1+ MB

In [32]:
usa_crimes_dataset.describe()

,Incident ID,CR Number,Victims,Zip Code,Address Number,Latitude,Longitude
count,3.060940e+05,3.060940e+05,306094.000000,302915.000000,2.799850e+05,306094.000000,306094.000000
mean,2.012369e+08,1.692787e+08,1.022692,20876.535939,8.393001e+03,38.146328,-75.269490
std,8.626185e+04,6.210304e+07,0.192311,170.157722,1.526296e+04,5.974082,11.786118
min,2.010871e+08,1.001107e+07,1.000000,6.000000,1.000000e+00,0.000000,-77.516753
25%,2.011625e+08,1.705431e+08,1.000000,20853.000000,1.600000e+03,39.020392,-77.197117
50%,2.012361e+08,1.900183e+08,1.000000,20878.000000,8.100000e+03,39.072844,-77.099464
75%,2.013109e+08,2.000466e+08,1.000000,20904.000000,1.250000e+04,39.142072,-77.029046
max,2.013872e+08,2.204211e+08,22.000000,29882.000000,2.090600e+06,90.000000,0.000000

> **sum of null values**

In [33]:
usa_crimes_dataset.isna().sum()

Incident ID                    0
Offence Code                   0
CR Number                      0
Dispatch Date / Time       49029
NIBRS Code                     0
Victims                        0
Crime Name1                  272
Crime Name2                  272
Crime Name3                  272
Police District Name          94
Block Address              26206
City                        1276
State                          0
Zip Code                    3179
Agency                         0
Place                          0
Sector                      1530
Beat                        1530
PRA                          239
Address Number             26109
Street Prefix             292463
Street Name                    1
Street Suffix             300662
Street Type                  339
Start_Date_Time                0
End_Date_Time             161658
Latitude                       0
Longitude                      0
Police District Number         0
Location                       0
dtype: int64

> **filling null values of "Dispatch Date / Time"**

In [34]:
usa_crimes_dataset[usa_crimes_dataset['Dispatch Date / Time'].isnull()][['Incident ID', 'Dispatch Date / Time', 'Start_Date_Time']]

        Incident ID Dispatch Date / Time         Start_Date_Time
6         201121509                  NaN  02/18/2017 12:18:00 AM
7         201091648                  NaN  07/31/2016 11:00:00 PM
8         201108886                  NaN  11/20/2016 09:00:00 AM
9         201124327                  NaN  03/08/2017 02:03:00 PM
10        201096093                  NaN  08/28/2016 12:00:00 AM
...             ...                  ...                     ...
305089    201326516                  NaN  04/07/2021 05:20:00 PM
305097    201322579                  NaN  12/01/2020 10:23:00 AM
305538    201331625                  NaN  11/01/2020 03:00:00 PM
305608    201323218                  NaN  02/20/2021 12:00:00 AM
305624    201326306                  NaN  03/06/2021 06:27:00 AM

[49029 rows x 3 columns]

In [35]:
time_diff = pd.to_datetime(usa_crimes_dataset['Dispatch Date / Time']) - pd.to_datetime(usa_crimes_dataset['Start_Date_Time'])

mean_time_diff = time_diff.mean()
mode_time_diff = time_diff.mode()[0]

print(f'Mean time difference = {mean_time_diff}')
print(f'Mode time difference = {mode_time_diff}')

usa_crimes_dataset['Dispatch Date / Time'].fillna(pd.to_datetime(usa_crimes_dataset['Start_Date_Time']) + mode_time_diff, inplace=True)

<ipython-input-35-1e230245d168>:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  time_diff = pd.to_datetime(usa_crimes_dataset['Dispatch Date / Time']) - pd.to_datetime(usa_crimes_dataset['Start_Date_Time'])
<ipython-input-35-1e230245d168>:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  time_diff = pd.to_datetime(usa_crimes_dataset['Dispatch Date / Time']) - pd.to_datetime(usa_crimes_dataset['Start_Date_Time'])

Mean time difference = 8 days 01:09:45.063038531
Mode time difference = 0 days 00:00:23

<ipython-input-35-1e230245d168>:9: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  usa_crimes_dataset['Dispatch Date / Time'].fillna(pd.to_datetime(usa_crimes_dataset['Start_Date_Time']) + mode_time_diff, inplace=True)
<ipython-input-35-1e230245d168>:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  usa_crimes_dataset['Dispatch Date / Time'].fillna(pd.to_datetime(usa_crimes_dataset['Start_Date_Time']) + mode_time_diff, inplace=True)

> **filling of null values of "city" column according to "zip code" column**

In [36]:
null_city_rows = usa_crimes_dataset[usa_crimes_dataset['City'].isnull()]
null_city_rows[['City', 'Zip Code']]

       City  Zip Code
358     NaN   20912.0
398     NaN   20912.0
905     NaN   20912.0
1559    NaN   20910.0
1896    NaN   20912.0
...     ...       ...
305623  NaN   20912.0
305750  NaN   20912.0
305803  NaN   20912.0
305854  NaN   20912.0
305923  NaN   20912.0

[1276 rows x 2 columns]

In [37]:
zip_to_city = usa_crimes_dataset[usa_crimes_dataset['City'].notnull()].drop_duplicates('Zip Code').set_index('Zip Code')['City']
usa_crimes_dataset['City'] = usa_crimes_dataset['City'].fillna(usa_crimes_dataset['Zip Code'].map(zip_to_city))

In [38]:
null_city_rows = usa_crimes_dataset[usa_crimes_dataset['City'].isnull()]
null_city_rows

Empty DataFrame
Columns: [Incident ID, Offence Code, CR Number, Dispatch Date / Time, NIBRS Code, Victims, Crime Name1, Crime Name2, Crime Name3, Police District Name, Block Address, City, State, Zip Code, Agency, Place, Sector, Beat, PRA, Address Number, Street Prefix, Street Name, Street Suffix, Street Type, Start_Date_Time, End_Date_Time, Latitude, Longitude, Police District Number, Location]
Index: []

[0 rows x 30 columns]

> **deleting of columns that they have many null values and we don't need during analysis**

In [39]:
dropping_columns = ['Street Prefix', 'Street Suffix', 'End_Date_Time', 'Block Address', 'Address Number', 'PRA']
usa_crimes_dataset = usa_crimes_dataset.drop(columns = dropping_columns)

In [40]:
usa_crimes_dataset.isna().sum()

Incident ID                  0
Offence Code                 0
CR Number                    0
Dispatch Date / Time         0
NIBRS Code                   0
Victims                      0
Crime Name1                272
Crime Name2                272
Crime Name3                272
Police District Name        94
City                         0
State                        0
Zip Code                  3179
Agency                       0
Place                        0
Sector                    1530
Beat                      1530
Street Name                  1
Street Type                339
Start_Date_Time              0
Latitude                     0
Longitude                    0
Police District Number       0
Location                     0
dtype: int64

> **deleting rows that "latitude", "longitude" columns have "0" value**

In [41]:
columns_have_zero = ['Latitude', 'Longitude']

for column in columns_have_zero:
  usa_crimes_dataset = usa_crimes_dataset.drop(usa_crimes_dataset[usa_crimes_dataset[column] == 0].index)

> **deleting rows that "city" column have digit values**

In [42]:
columns_have_digits = ['City', 'State']

for column in columns_have_digits:
  usa_crimes_dataset = usa_crimes_dataset.drop(usa_crimes_dataset[(usa_crimes_dataset[column]).apply(lambda value: str(value).isdigit())].index)



> **replacing data in "Beat" column that has non-alphanumeric characters**

In [43]:
usa_crimes_dataset['Beat'] = usa_crimes_dataset['Beat'].str.replace(r'[^a-zA-Z0-9]', '', regex=True)

> **deleting rows that have null values in them**

In [44]:
columns_have_null = ['Crime Name1', 'Police District Name', 'Zip Code', 'Beat', 'Street Name', 'Street Type']

for column in columns_have_null:
  usa_crimes_dataset = usa_crimes_dataset.dropna(subset = [column])

In [45]:
usa_crimes_dataset.isna().sum()

Incident ID               0
Offence Code              0
CR Number                 0
Dispatch Date / Time      0
NIBRS Code                0
Victims                   0
Crime Name1               0
Crime Name2               0
Crime Name3               0
Police District Name      0
City                      0
State                     0
Zip Code                  0
Agency                    0
Place                     0
Sector                    0
Beat                      0
Street Name               0
Street Type               0
Start_Date_Time           0
Latitude                  0
Longitude                 0
Police District Number    0
Location                  0
dtype: int64

In [46]:
usa_crimes_dataset

,Incident ID,Offence Code,CR Number,Dispatch Date / Time,NIBRS Code,Victims,Crime Name1,Crime Name2,Crime Name3,Police District Name,...,Place,Sector,Beat,Street Name,Street Type,Start_Date_Time,Latitude,Longitude,Police District Number,Location
0,201202980,3550,180042096,08/23/2018 09:52:08 PM,35B,1,Crime Against Society,Drug Equipment Violations,DRUGS - NARCOTIC EQUIP - POSSESS,GERMANTOWN,...,Street - In vehicle,N,5N1,MIDDLEBROOK,RD,08/23/2018 09:52:00 PM,39.177744,-77.265619,5D,"(39.1777, -77.2656)"
1,201181293,3522,180015424,03/30/2018 01:00:55 AM,35A,1,Crime Against Society,Drug/Narcotic Violations,DRUGS - OPIUM OR DERIVATIVE - POSSESS,BETHESDA,...,Street - In vehicle,E,2E2,WOODMONT,AVE,03/30/2018 01:01:00 AM,38.992693,-77.097063,2D,"(38.9927, -77.0971)"
2,201181293,3562,180015424,03/30/2018 01:00:55 AM,35A,1,Crime Against Society,Drug/Narcotic Violations,DRUGS - MARIJUANA - POSSESS,BETHESDA,...,Street - In vehicle,E,2E2,WOODMONT,AVE,03/30/2018 01:01:00 AM,38.992693,-77.097063,2D,"(38.9927, -77.0971)"
3,201193163,3520,180029476,06/14/2018 10:26:45 PM,35A,1,Crime Against Society,Drug/Narcotic Violations,DRUGS - OPIUM OR DERIVATIVE - SELL,MONTGOMERY VILLAGE,...,Hotel/Motel/Etc.,P,6P2,QUINCE ORCHARD,RD,06/14/2018 10:26:00 PM,39.147954,-77.218189,6D,"(39.148, -77.2182)"
4,201204355,2204,180043926,09/03/2018 12:06:54 PM,220,1,Crime Against Property,Burglary/Breaking and Entering,BURGLARY - NO FORCED ENTRY-RESIDENTIAL,BETHESDA,...,Residence - Single Family,E,2E1,FALSTONE,AVE,09/02/2018 11:30:00 PM,38.966174,-77.096561,2D,"(38.9662, -77.0966)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
306089,201320571,1399,210006666,02/21/2021 07:25:28 AM,13B,1,Crime Against Person,Simple Assault,ASSAULT - 2ND DEGREE,MONTGOMERY VILLAGE,...,Residence -Townhouse/Duplex,R,6R2,TRANSHIRE,RD,02/20/2021 08:00:00 PM,39.172701,-77.197340,6D,"(39.1727, -77.1973)"
306090,201329875,2305,210017101,05/06/2021 10:54:47 PM,23F,1,Crime Against Property,Theft From Motor Vehicle,LARCENY - FROM AUTO,WHEATON,...,Parking Lot - Residential,K,4K2,ATHERTON,DR,05/06/2021 03:15:00 AM,39.059672,-77.075995,4D,"(39.0597, -77.076)"
306091,201329751,5016,210016952,05/05/2021 10:38:58 PM,90Z,1,Crime Against Society,All Other Offenses,OBSTRUCT GOVT - VIOLATION OF A COURT ORDER,GERMANTOWN,...,Residence - Apartment/Condo,N,5N1,BALTUSROL,DR,05/05/2021 10:38:00 PM,39.199722,-77.273039,5D,"(39.1997, -77.273)"
306092,201323117,9099,210009468,03/13/2021 12:07:14 PM,90Z,1,Crime Against Society,All Other Offenses,ALL OTHER OFFENSES,SILVER SPRING,...,Street - Other,G,3G1,FENTON,ST,03/13/2021 01:35:00 PM,38.985813,-77.022915,3D,"(38.9858, -77.0229)"
306093,201327806,2305,210014587,04/19/2021 02:17:29 PM,23F,1,Crime Against Property,Theft From Motor Vehicle,LARCENY - FROM AUTO,BETHESDA,...,Street - Residential,D,2D3,NEWPORT MILL,RD,04/18/2021 04:00:00 PM,39.037115,-77.072485,2D,"(39.0371, -77.0725)"

> **changing datatypes of columns**

In [47]:
usa_crimes_dataset.dtypes

Incident ID                 int64
Offence Code               object
CR Number                   int64
Dispatch Date / Time       object
NIBRS Code                 object
Victims                     int64
Crime Name1                object
Crime Name2                object
Crime Name3                object
Police District Name       object
City                       object
State                      object
Zip Code                  float64
Agency                     object
Place                      object
Sector                     object
Beat                       object
Street Name                object
Street Type                object
Start_Date_Time            object
Latitude                  float64
Longitude                 float64
Police District Number     object
Location                   object
dtype: object

In [48]:
usa_crimes_dataset['Zip Code'] = (usa_crimes_dataset['Zip Code'].astype('int64')).astype('str')

> **adding id column**

In [49]:
duplicate_counts = usa_crimes_dataset['Incident ID'].value_counts()
duplicates = duplicate_counts[duplicate_counts > 1]
duplicates

Incident ID
201168542    9
201189600    8
201231948    8
201087295    8
201267256    8
            ..
201153805    2
201246732    2
201251614    2
201162273    2
201155317    2
Name: count, Length: 19738, dtype: int64

In [50]:
usa_crimes_dataset.insert(0, 'id', [id for id in range(100001, len(usa_crimes_dataset) + 100001)])

> **seperating date and time columns**

In [51]:
date_time_columns = {
    'Dispatch Date / Time' : ['Dispatch Date', 'Dispatch Time'],
    'Start_Date_Time' : ['Start Date', 'Start Time']
}

for column in date_time_columns:
  usa_crimes_dataset[column] = pd.to_datetime(usa_crimes_dataset[column], format='%m/%d/%Y %I:%M:%S %p')
  usa_crimes_dataset[date_time_columns[column][0]] = usa_crimes_dataset[column].dt.date
  usa_crimes_dataset[date_time_columns[column][1]] = usa_crimes_dataset[column].dt.time
  usa_crimes_dataset = usa_crimes_dataset.drop(column, axis=1)

usa_crimes_dataset

,id,Incident ID,Offence Code,CR Number,NIBRS Code,Victims,Crime Name1,Crime Name2,Crime Name3,Police District Name,...,Street Name,Street Type,Latitude,Longitude,Police District Number,Location,Dispatch Date,Dispatch Time,Start Date,Start Time
0,100001,201202980,3550,180042096,35B,1,Crime Against Society,Drug Equipment Violations,DRUGS - NARCOTIC EQUIP - POSSESS,GERMANTOWN,...,MIDDLEBROOK,RD,39.177744,-77.265619,5D,"(39.1777, -77.2656)",2018-08-23,21:52:08,2018-08-23,21:52:00
1,100002,201181293,3522,180015424,35A,1,Crime Against Society,Drug/Narcotic Violations,DRUGS - OPIUM OR DERIVATIVE - POSSESS,BETHESDA,...,WOODMONT,AVE,38.992693,-77.097063,2D,"(38.9927, -77.0971)",2018-03-30,01:00:55,2018-03-30,01:01:00
2,100003,201181293,3562,180015424,35A,1,Crime Against Society,Drug/Narcotic Violations,DRUGS - MARIJUANA - POSSESS,BETHESDA,...,WOODMONT,AVE,38.992693,-77.097063,2D,"(38.9927, -77.0971)",2018-03-30,01:00:55,2018-03-30,01:01:00
3,100004,201193163,3520,180029476,35A,1,Crime Against Society,Drug/Narcotic Violations,DRUGS - OPIUM OR DERIVATIVE - SELL,MONTGOMERY VILLAGE,...,QUINCE ORCHARD,RD,39.147954,-77.218189,6D,"(39.148, -77.2182)",2018-06-14,22:26:45,2018-06-14,22:26:00
4,100005,201204355,2204,180043926,220,1,Crime Against Property,Burglary/Breaking and Entering,BURGLARY - NO FORCED ENTRY-RESIDENTIAL,BETHESDA,...,FALSTONE,AVE,38.966174,-77.096561,2D,"(38.9662, -77.0966)",2018-09-03,12:06:54,2018-09-02,23:30:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
306089,393617,201320571,1399,210006666,13B,1,Crime Against Person,Simple Assault,ASSAULT - 2ND DEGREE,MONTGOMERY VILLAGE,...,TRANSHIRE,RD,39.172701,-77.197340,6D,"(39.1727, -77.1973)",2021-02-21,07:25:28,2021-02-20,20:00:00
306090,393618,201329875,2305,210017101,23F,1,Crime Against Property,Theft From Motor Vehicle,LARCENY - FROM AUTO,WHEATON,...,ATHERTON,DR,39.059672,-77.075995,4D,"(39.0597, -77.076)",2021-05-06,22:54:47,2021-05-06,03:15:00
306091,393619,201329751,5016,210016952,90Z,1,Crime Against Society,All Other Offenses,OBSTRUCT GOVT - VIOLATION OF A COURT ORDER,GERMANTOWN,...,BALTUSROL,DR,39.199722,-77.273039,5D,"(39.1997, -77.273)",2021-05-05,22:38:58,2021-05-05,22:38:00
306092,393620,201323117,9099,210009468,90Z,1,Crime Against Society,All Other Offenses,ALL OTHER OFFENSES,SILVER SPRING,...,FENTON,ST,38.985813,-77.022915,3D,"(38.9858, -77.0229)",2021-03-13,12:07:14,2021-03-13,13:35:00
306093,393621,201327806,2305,210014587,23F,1,Crime Against Property,Theft From Motor Vehicle,LARCENY - FROM AUTO,BETHESDA,...,NEWPORT MILL,RD,39.037115,-77.072485,2D,"(39.0371, -77.0725)",2021-04-19,14:17:29,2021-04-18,16:00:00

> **changing names of columns**

In [52]:
usa_crimes_dataset.columns

Index(['id', 'Incident ID', 'Offence Code', 'CR Number', 'NIBRS Code',
       'Victims', 'Crime Name1', 'Crime Name2', 'Crime Name3',
       'Police District Name', 'City', 'State', 'Zip Code', 'Agency', 'Place',
       'Sector', 'Beat', 'Street Name', 'Street Type', 'Latitude', 'Longitude',
       'Police District Number', 'Location', 'Dispatch Date', 'Dispatch Time',
       'Start Date', 'Start Time'],
      dtype='object')

In [53]:
usa_crimes_dataset.rename(columns={'Incident ID': 'incident_id',
                       'Offence Code': 'offence_code',
                       'CR Number': 'cr_number',
                       'NIBRS Code': 'nibrs_code',
                       'Victims': 'victims',
                       'Crime Name1': 'crime_type',
                       'Crime Name2': 'crime_category',
                       'Crime Name3': 'crime_information',
                       'Police District Name': 'police_district_name',
                       'City': 'city',
                       'State': 'state',
                       'Zip Code': 'zip_code',
                       'Agency': 'agency',
                       'Place': 'place',
                       'Sector': 'sector',
                       'Beat': 'beat',
                       'Street Name': 'street_name',
                       'Street Type': 'street_type',
                       'Latitude': 'latitude',
                       'Longitude': 'longitude',
                       'Police District Number': 'police_district_number',
                       'Location': 'location',
                       'Dispatch Date': 'dispatch_date',
                       'Dispatch Time': 'dispatch_time',
                       'Start Date': 'start_date',
                       'Start Time': 'start_time'}, inplace=True)

In [54]:
usa_crimes_dataset.columns

Index(['id', 'incident_id', 'offence_code', 'cr_number', 'nibrs_code',
       'victims', 'crime_type', 'crime_category', 'crime_information',
       'police_district_name', 'city', 'state', 'zip_code', 'agency', 'place',
       'sector', 'beat', 'street_name', 'street_type', 'latitude', 'longitude',
       'police_district_number', 'location', 'dispatch_date', 'dispatch_time',
       'start_date', 'start_time'],
      dtype='object')

In [55]:
usa_crimes_dataset.info()

<class 'pandas.core.frame.DataFrame'>
Index: 293621 entries, 0 to 306093
Data columns (total 27 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   id                      293621 non-null  int64
 1   incident_id             293621 non-null  int64
 2   offence_code            293621 non-null  object
 3   cr_number               293621 non-null  int64
 4   nibrs_code              293621 non-null  object
 5   victims                 293621 non-null  int64
 6   crime_type              293621 non-null  object
 7   crime_category          293621 non-null  object
 8   crime_information       293621 non-null  object
 9   police_district_name    293621 non-null  object
 10  city                    293621 non-null  object
 11  state                   293621 non-null  object
 12  zip_code                293621 non-null  object
 13  agency                  293621 non-null  object
 14  place                   293621 non-null  object
 15  sector                  293621 non-null  object
 16  beat                    293621 non-null  object
 17  street_name             293621 non-null  object
 18  street_type             293621 non-null  object
 19  latitude                293621 non-null  float64
 20  longitude               293621 non-null  float64
 21  police_district_number  293621 non-null  object
 22  location                293621 non-null  object
 23  dispatch_date           293621 non-null  object
 24  dispatch_time           293621 non-null  object
 25  start_date              293621 non-null  object
 26  start_time              293621 non-null  object
dtypes: float64(2), int64(4), object(21)
memory usage: 62.7+ MB

> **adding part of day according to time**

In [56]:
def get_part_of_day(time):
  if (12 > int((str(time).split(':'))[0]) > 6):
    return 'Morning'
  elif (int((str(time).split(':'))[0]) == 6 and int((str(time).split(':'))[1]) == 0 and int((str(time).split(':'))[2]) == 0):
    return 'Morning'
  elif (int((str(time).split(':'))[0]) == 12 and int((str(time).split(':'))[1]) == 0 and int((str(time).split(':'))[2]) == 0):
    return 'Morning'
  elif (17 > int((str(time).split(':'))[0]) >= 12):
    return 'Afternoon'
  elif (int((str(time).split(':'))[0]) == 12 and int((str(time).split(':'))[1]) > 0 and int((str(time).split(':'))[2]) > 0):
    return 'Afternoon'
  elif (int((str(time).split(':'))[0]) == 17 and int((str(time).split(':'))[1]) == 0 and int((str(time).split(':'))[2]) == 0):
    return 'Afternoon'
  elif (20 > int((str(time).split(':'))[0]) >= 17):
    return 'Evening'
  elif (int((str(time).split(':'))[0]) == 17 and int((str(time).split(':'))[1]) > 0 and int((str(time).split(':'))[2]) > 0):
    return 'Evening'
  elif (int((str(time).split(':'))[0]) == 20 and int((str(time).split(':'))[1]) == 0 and int((str(time).split(':'))[2]) == 0):
    return 'Evening'
  else:
    return 'Night'


part_of_day = []
for index, start_time in enumerate(usa_crimes_dataset['start_time']):
  part_of_day.append(get_part_of_day(start_time))

usa_crimes_dataset.insert(len(usa_crimes_dataset.columns), 'start_part_of_day', part_of_day)

usa_crimes_dataset

,id,incident_id,offence_code,cr_number,nibrs_code,victims,crime_type,crime_category,crime_information,police_district_name,...,street_type,latitude,longitude,police_district_number,location,dispatch_date,dispatch_time,start_date,start_time,start_part_of_day
0,100001,201202980,3550,180042096,35B,1,Crime Against Society,Drug Equipment Violations,DRUGS - NARCOTIC EQUIP - POSSESS,GERMANTOWN,...,RD,39.177744,-77.265619,5D,"(39.1777, -77.2656)",2018-08-23,21:52:08,2018-08-23,21:52:00,Night
1,100002,201181293,3522,180015424,35A,1,Crime Against Society,Drug/Narcotic Violations,DRUGS - OPIUM OR DERIVATIVE - POSSESS,BETHESDA,...,AVE,38.992693,-77.097063,2D,"(38.9927, -77.0971)",2018-03-30,01:00:55,2018-03-30,01:01:00,Night
2,100003,201181293,3562,180015424,35A,1,Crime Against Society,Drug/Narcotic Violations,DRUGS - MARIJUANA - POSSESS,BETHESDA,...,AVE,38.992693,-77.097063,2D,"(38.9927, -77.0971)",2018-03-30,01:00:55,2018-03-30,01:01:00,Night
3,100004,201193163,3520,180029476,35A,1,Crime Against Society,Drug/Narcotic Violations,DRUGS - OPIUM OR DERIVATIVE - SELL,MONTGOMERY VILLAGE,...,RD,39.147954,-77.218189,6D,"(39.148, -77.2182)",2018-06-14,22:26:45,2018-06-14,22:26:00,Night
4,100005,201204355,2204,180043926,220,1,Crime Against Property,Burglary/Breaking and Entering,BURGLARY - NO FORCED ENTRY-RESIDENTIAL,BETHESDA,...,AVE,38.966174,-77.096561,2D,"(38.9662, -77.0966)",2018-09-03,12:06:54,2018-09-02,23:30:00,Night
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
306089,393617,201320571,1399,210006666,13B,1,Crime Against Person,Simple Assault,ASSAULT - 2ND DEGREE,MONTGOMERY VILLAGE,...,RD,39.172701,-77.197340,6D,"(39.1727, -77.1973)",2021-02-21,07:25:28,2021-02-20,20:00:00,Evening
306090,393618,201329875,2305,210017101,23F,1,Crime Against Property,Theft From Motor Vehicle,LARCENY - FROM AUTO,WHEATON,...,DR,39.059672,-77.075995,4D,"(39.0597, -77.076)",2021-05-06,22:54:47,2021-05-06,03:15:00,Night
306091,393619,201329751,5016,210016952,90Z,1,Crime Against Society,All Other Offenses,OBSTRUCT GOVT - VIOLATION OF A COURT ORDER,GERMANTOWN,...,DR,39.199722,-77.273039,5D,"(39.1997, -77.273)",2021-05-05,22:38:58,2021-05-05,22:38:00,Night
306092,393620,201323117,9099,210009468,90Z,1,Crime Against Society,All Other Offenses,ALL OTHER OFFENSES,SILVER SPRING,...,ST,38.985813,-77.022915,3D,"(38.9858, -77.0229)",2021-03-13,12:07:14,2021-03-13,13:35:00,Afternoon
306093,393621,201327806,2305,210014587,23F,1,Crime Against Property,Theft From Motor Vehicle,LARCENY - FROM AUTO,BETHESDA,...,RD,39.037115,-77.072485,2D,"(39.0371, -77.0725)",2021-04-19,14:17:29,2021-04-18,16:00:00,Afternoon


> **adding day of week according to date**

In [57]:
usa_crimes_dataset['start_day_of_week'] = (pd.to_datetime(usa_crimes_dataset['start_date'])).dt.day_name()
usa_crimes_dataset

,id,incident_id,offence_code,cr_number,nibrs_code,victims,crime_type,crime_category,crime_information,police_district_name,...,latitude,longitude,police_district_number,location,dispatch_date,dispatch_time,start_date,start_time,start_part_of_day,start_day_of_week
0,100001,201202980,3550,180042096,35B,1,Crime Against Society,Drug Equipment Violations,DRUGS - NARCOTIC EQUIP - POSSESS,GERMANTOWN,...,39.177744,-77.265619,5D,"(39.1777, -77.2656)",2018-08-23,21:52:08,2018-08-23,21:52:00,Night,Thursday
1,100002,201181293,3522,180015424,35A,1,Crime Against Society,Drug/Narcotic Violations,DRUGS - OPIUM OR DERIVATIVE - POSSESS,BETHESDA,...,38.992693,-77.097063,2D,"(38.9927, -77.0971)",2018-03-30,01:00:55,2018-03-30,01:01:00,Night,Friday
2,100003,201181293,3562,180015424,35A,1,Crime Against Society,Drug/Narcotic Violations,DRUGS - MARIJUANA - POSSESS,BETHESDA,...,38.992693,-77.097063,2D,"(38.9927, -77.0971)",2018-03-30,01:00:55,2018-03-30,01:01:00,Night,Friday
3,100004,201193163,3520,180029476,35A,1,Crime Against Society,Drug/Narcotic Violations,DRUGS - OPIUM OR DERIVATIVE - SELL,MONTGOMERY VILLAGE,...,39.147954,-77.218189,6D,"(39.148, -77.2182)",2018-06-14,22:26:45,2018-06-14,22:26:00,Night,Thursday
4,100005,201204355,2204,180043926,220,1,Crime Against Property,Burglary/Breaking and Entering,BURGLARY - NO FORCED ENTRY-RESIDENTIAL,BETHESDA,...,38.966174,-77.096561,2D,"(38.9662, -77.0966)",2018-09-03,12:06:54,2018-09-02,23:30:00,Night,Sunday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
306089,393617,201320571,1399,210006666,13B,1,Crime Against Person,Simple Assault,ASSAULT - 2ND DEGREE,MONTGOMERY VILLAGE,...,39.172701,-77.197340,6D,"(39.1727, -77.1973)",2021-02-21,07:25:28,2021-02-20,20:00:00,Evening,Saturday
306090,393618,201329875,2305,210017101,23F,1,Crime Against Property,Theft From Motor Vehicle,LARCENY - FROM AUTO,WHEATON,...,39.059672,-77.075995,4D,"(39.0597, -77.076)",2021-05-06,22:54:47,2021-05-06,03:15:00,Night,Thursday
306091,393619,201329751,5016,210016952,90Z,1,Crime Against Society,All Other Offenses,OBSTRUCT GOVT - VIOLATION OF A COURT ORDER,GERMANTOWN,...,39.199722,-77.273039,5D,"(39.1997, -77.273)",2021-05-05,22:38:58,2021-05-05,22:38:00,Night,Wednesday
306092,393620,201323117,9099,210009468,90Z,1,Crime Against Society,All Other Offenses,ALL OTHER OFFENSES,SILVER SPRING,...,38.985813,-77.022915,3D,"(38.9858, -77.0229)",2021-03-13,12:07:14,2021-03-13,13:35:00,Afternoon,Saturday
306093,393621,201327806,2305,210014587,23F,1,Crime Against Property,Theft From Motor Vehicle,LARCENY - FROM AUTO,BETHESDA,...,39.037115,-77.072485,2D,"(39.0371, -77.0725)",2021-04-19,14:17:29,2021-04-18,16:00:00,Afternoon,Sunday

> **downloading of cleaned data**

In [60]:
from google.colab import files
usa_crimes_dataset.to_csv('usa_crimes_dataset_cleaned.csv', index=False)
files.download('usa_crimes_dataset_cleaned.csv')